module.exports = [
  'abcdeccdddefghdjkkjjjkdc',
  'babcdbbcccdfghchjkhhjkbc',
  'cbadebcdccdfghbjkkjjjkbc',
  'dcdabcccddefghejkkjjkkdc',
  'edebbdcdeefghhfjkkjjkkdc',
  'cbbcdabcccdfghcjkkjjjkbc',
  'cbcccbacccdeghdjkkjjjkbc',
  'dcdcdccabcceghejkkjjjkbc',
  'dccdeccbabcdfgdjkkjjjkbb',
  'dccdecccbaccfgdhjkjjjkbc',
  'eddefddcccabdeejkkjjjkbc',
  'ffffgfeedcbacefkkkkkkkdc',
  'gggghgggffdcadgkkkkkkkfe',
  'hhhhhhhhggeedahkkkkkkkhg',
  'dbcfecddedfehgajkkkjjkce',
  'jhjjjjjjjhjkkkjzzzzzzzhj',
  'kjkkkkkkkjkkkkkzzzzzzzjk',
  'kkkkkkkkkkkkkkkzzzzzzzkk',
  'jhjjjjjjjjjkkkkzzzzzzzjk',
  'jhjjjjjjjjjkkkjzzzzzzzhj',
  'jjjkkjjjjjjkkkjzzzzzzzjk',
  'kkkkkkkkkkkkkkkzzzzzzzjk',
  'cbbccbbcbbcdfhchjkjhjjac',
  'dccddccbbcbcegejkkkjkkca'
]

// module.exports = {
//   1: 'abcdeccdddefghdjkkjjjkdc',
//   2: 'babcdbbcccdfghchjkhhjkbc',
//   3: 'cbadebcdccdfghbjkkjjjkbc',
//   4: 'dcdabcccddefghejkkjjkkdc',
//   5: 'edebbdcdeefghhfjkkjjkkdc',
//   6: 'cbbcdabcccdfghcjkkjjjkbc',
//   7: 'cbcccbacccdeghdjkkjjjkbc',
//   8: 'dcdcdccabcceghejkkjjjkbc',
//   9: 'dccdeccbabcdfgdjkkjjjkbb',
//   10: 'dccdecccbaccfgdhjkjjjkbc',
//   11: 'eddefddcccabdeejkkjjjkbc',
//   12: 'ffffgfeedcbacefkkkkkkkdc',
//   13: 'gggghgggffdcadgkkkkkkkfe',
//   14: 'hhhhhhhhggeedahkkkkkkkhg',
//   15: 'dbcfecddedfehgajkkkjjkce',
//   16: 'jhjjjjjjjhjkkkjzzzzzzzhj',
//   17: 'kjkkkkkkkjkkkkkzzzzzzzjk',
//   18: 'kkkkkkkkkkkkkkkzzzzzzzkk',
//   19: 'jhjjjjjjjjjkkkkzzzzzzzjk',
//   20: 'jhjjjjjjjjjkkkjzzzzzzzhj',
//   21: 'jjjkkjjjjjjkkkjzzzzzzzjk',
//   22: 'kkkkkkkkkkkkkkkzzzzzzzjk',
//   23: 'cbbccbbcbbcdfhchjkjhjjac',
//   24: 'dccddccbbcbcegejkkkjkkca'
// }
